# Generated by Django 4.2.30 on 2026-06-15 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdraft',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_cart_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_sale_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
