# Generated by Django 4.2.30 on 2026-06-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('hold', 'Hold'), ('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('order_void', 'Void'), ('due', 'Due'), ('partially_due', 'Partially Due')], default='unpaid', max_length=30),
        ),
    ]
