# Generated by Django 4.2.30 on 2026-06-16 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('sales', '0002_alter_cartdraft_customer_alter_returnorder_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='unit_quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='catalog.productunitquantity'),
        ),
    ]
