# Generated by Django 4.2.30 on 2026-06-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesetting_salecoupon_returnitemtax_salestorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='order_type',
            field=models.CharField(choices=[('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='takeaway', max_length=20),
        ),
    ]
