# Generated by Django 4.2.30 on 2026-06-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_saleorder_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleaddress',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='saleaddress',
            name='company',
        ),
        migrations.RemoveField(
            model_name='saleaddress',
            name='sale_order',
        ),
        migrations.RemoveField(
            model_name='salenote',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='salenote',
            name='company',
        ),
        migrations.RemoveField(
            model_name='salenote',
            name='sale_order',
        ),
        migrations.RemoveField(
            model_name='salesetting',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='salesetting',
            name='company',
        ),
        migrations.RemoveField(
            model_name='salesetting',
            name='sale_order',
        ),
        migrations.AlterUniqueTogether(
            name='salestorage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='salestorage',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='salestorage',
            name='company',
        ),
        migrations.RemoveField(
            model_name='salestorage',
            name='sale_order',
        ),
        migrations.RemoveField(
            model_name='saletax',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='saletax',
            name='company',
        ),
        migrations.RemoveField(
            model_name='saletax',
            name='sale_order',
        ),
        migrations.RemoveField(
            model_name='saletax',
            name='tax',
        ),
        migrations.DeleteModel(
            name='ReturnItemTax',
        ),
        migrations.DeleteModel(
            name='SaleAddress',
        ),
        migrations.DeleteModel(
            name='SaleNote',
        ),
        migrations.DeleteModel(
            name='SaleSetting',
        ),
        migrations.DeleteModel(
            name='SaleStorage',
        ),
        migrations.DeleteModel(
            name='SaleTax',
        ),
    ]
