# Generated by Django 4.2.30 on 2026-06-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_saleaddress_branch_remove_saleaddress_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleCoupon',
        ),
    ]
