# Generated by Django 4.2.30 on 2026-06-15 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_cartdraft_customer_alter_returnorder_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Deactive'), (2, 'Delete')], default=0, help_text='0: Active, 1: Inactive, 2: Deleted. Higher values are reserved for model-specific lifecycle states.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('usage', models.PositiveIntegerField(default=0)),
                ('limit_usage', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Deactive'), (2, 'Delete')], default=0, help_text='0: Active, 1: Inactive, 2: Deleted. Higher values are reserved for model-specific lifecycle states.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reward_name', models.CharField(blank=True, default='', max_length=150)),
                ('points', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('target', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='group',
        ),
        migrations.RemoveField(
            model_name='customercreditledger',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='customercreditledger',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customercreditledger',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerwallettransaction',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='customerwallettransaction',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customerwallettransaction',
            name='customer',
        ),
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'ordering': ['customer_id', 'type']},
        ),
        migrations.AlterUniqueTogether(
            name='customergroup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customeraccounthistory',
            name='action',
        ),
        migrations.RemoveField(
            model_name='customeraccounthistory',
            name='balance_after',
        ),
        migrations.RemoveField(
            model_name='customeraccounthistory',
            name='balance_before',
        ),
        migrations.RemoveField(
            model_name='customeraccounthistory',
            name='note',
        ),
        migrations.RemoveField(
            model_name='customeraccounthistory',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='customeraccounthistory',
            name='reference_type',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='state',
        ),
        migrations.AddField(
            model_name='customeraccounthistory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customeraccounthistory',
            name='next_amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='customeraccounthistory',
            name='operation',
            field=models.CharField(choices=[('deduct', 'Deduct'), ('refund', 'Refund'), ('add', 'Add'), ('payment', 'Payment')], default='add', max_length=20),
        ),
        migrations.AddField(
            model_name='customeraccounthistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_account_history', to='sales.saleorder'),
        ),
        migrations.AddField(
            model_name='customeraccounthistory',
            name='previous_amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='address_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='address_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='first_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='last_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='pobox',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='type',
            field=models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], default='billing', max_length=20),
        ),
        migrations.AddField(
            model_name='customergroup',
            name='minimal_credit_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum percentage the customer must pay when creating a credit sale.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='customeraccounthistory',
            name='amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='customeraccounthistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='customeraddress',
            constraint=models.UniqueConstraint(fields=('customer', 'type'), name='unique_customer_address_type'),
        ),
    ]
