# Generated by Codex on 2026-07-20

import django.core.validators
from django.db import migrations, models


def clamp_minimal_credit_payment(apps, schema_editor):
    CustomerGroup = apps.get_model("customers", "CustomerGroup")
    CustomerGroup.objects.filter(minimal_credit_payment__lt=0).update(minimal_credit_payment=0)
    CustomerGroup.objects.filter(minimal_credit_payment__gt=100).update(minimal_credit_payment=100)


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_alter_customergroup_unique_together"),
    ]

    operations = [
        migrations.RunPython(clamp_minimal_credit_payment, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="customergroup",
            name="minimal_credit_payment",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Minimum percentage the customer must pay when creating a credit sale.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="customergroup",
            constraint=models.CheckConstraint(
                check=models.Q(minimal_credit_payment__gte=0) & models.Q(minimal_credit_payment__lte=100),
                name="customer_group_minimal_credit_payment_percent",
            ),
        ),
    ]
