# Generated by Django 4.2.30 on 2026-06-15 20:10

import apps.customers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rewards', '0001_initial'),
        ('organizations', '0001_initial'),
        ('accounts', '0006_user_account_amount_user_birth_date_and_more'),
        ('promotions', '0001_initial'),
        ('sales', '0001_initial'),
        ('customers', '0003_customercoupon_customerreward_remove_customer_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergroup',
            name='reward_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_groups', to='rewards.rewardsystem'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerCreditLedger',
        ),
        migrations.DeleteModel(
            name='CustomerWalletTransaction',
        ),
        migrations.AddField(
            model_name='customerreward',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='customerreward',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='customerreward',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerreward',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerreward',
            name='reward',
            field=models.ForeignKey(db_column='reward_id', on_delete=django.db.models.deletion.CASCADE, related_name='customer_rewards', to='rewards.rewardsystem'),
        ),
        migrations.AddField(
            model_name='customercoupon',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='customercoupon',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='customercoupon',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customercoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_coupons', to='promotions.coupon'),
        ),
        migrations.AddField(
            model_name='customercoupon',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='customergroup',
            name='code',
        ),
        migrations.RemoveField(
            model_name='customergroup',
            name='credit_limit',
        ),
        migrations.AlterUniqueTogether(
            name='customerreward',
            unique_together={('customer', 'reward')},
        ),
        migrations.AlterUniqueTogether(
            name='customercoupon',
            unique_together={('customer', 'code')},
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'ordering': ['first_name', 'last_name', 'id'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', apps.customers.models.CustomerManager()),
            ],
        ),
    ]
