# Generated by Django 4.2.30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterModelTable(
            name="accesstoken",
            table="personal_access_tokens",
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
