# Generated by Django 4.2.30 on 2026-05-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_cashier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_store_manager',
            field=models.BooleanField(default=False),
        ),
    ]
