# Generated by Django 4.2.30 on 2026-06-15 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('accounts', '0005_remove_otprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='credit_limit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.customergroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='owed_amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='user',
            name='pobox',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='purchases_amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='user',
            name='total_sales',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='user',
            name='total_sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
