# Generated by Django 4.2.30 on 2026-05-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Deactive'), (2, 'Delete')], default=0, help_text='0: Active, 1: Inactive, 2: Deleted. Higher values are reserved for model-specific lifecycle states.'),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Deactive'), (2, 'Delete')], default=0, help_text='0: Active, 1: Inactive, 2: Deleted. Higher values are reserved for model-specific lifecycle states.'),
        ),
        migrations.AlterField(
            model_name='role',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Deactive'), (2, 'Delete')], default=0, help_text='0: Active, 1: Inactive, 2: Deleted. Higher values are reserved for model-specific lifecycle states.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('otp', 'OTP'), ('google', 'Google')], default='password', max_length=20),
        ),
    ]
