# Generated by Django 4.2.30 on 2026-06-15 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def backfill_user_role_relations(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    UserRoleRelation = apps.get_model('accounts', 'UserRoleRelation')

    for user in User.objects.exclude(role_id__isnull=True).iterator():
        UserRoleRelation.objects.get_or_create(
            user_id=user.id,
            role_id=user.role_id,
            defaults={"status": 0},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_account_amount_user_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Deactive'), (2, 'Delete')], default=0, help_text='0: Active, 1: Inactive, 2: Deleted. Higher values are reserved for model-specific lifecycle states.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'role_id'],
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.RunPython(backfill_user_role_relations, noop_reverse),
    ]
