# Generated by Codex on 2026-07-20

import django.core.validators
from django.db import migrations, models


def clamp_role_minimal_credit_payment(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    Role.objects.filter(minimal_credit_payment__lt=0).update(minimal_credit_payment=0)
    Role.objects.filter(minimal_credit_payment__gt=100).update(minimal_credit_payment=100)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_branch_full_name_unique_real"),
    ]

    operations = [
        migrations.RunPython(clamp_role_minimal_credit_payment, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="role",
            name="minimal_credit_payment",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                max_digits=18,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.CheckConstraint(
                check=models.Q(minimal_credit_payment__gte=0) & models.Q(minimal_credit_payment__lte=100),
                name="role_minimal_credit_payment_percent",
            ),
        ),
    ]
