# Generated by Django 4.2.30 on 2026-06-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userscope_permissionaccess_userwidget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('otp', 'OTP'), ('google', 'Google')], default='otp', max_length=20),
        ),
    ]
