# Generated by Django 4.2.30 on 2026-06-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_auth_provider'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userattribute',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userattribute',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userrolerelation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userrolerelation',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='userrolerelation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userrolerelation',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrolerelation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userscope',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='userscope',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userscope',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userwidget',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userwidget',
            name='user',
        ),
        migrations.DeleteModel(
            name='PermissionAccess',
        ),
        migrations.DeleteModel(
            name='UserAttribute',
        ),
        migrations.DeleteModel(
            name='UserRoleRelation',
        ),
        migrations.DeleteModel(
            name='UserScope',
        ),
        migrations.DeleteModel(
            name='UserWidget',
        ),
    ]
