# Generated by Django 4.2.30 on 2026-06-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssetting',
            name='allow_decimal_quantities',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesssetting',
            name='currency_precision',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='businesssetting',
            name='default_change_payment_type',
            field=models.CharField(default='cash-payment', max_length=80),
        ),
        migrations.AddField(
            model_name='businesssetting',
            name='hide_empty_categories',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesssetting',
            name='quick_product_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesssetting',
            name='show_quantity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesssetting',
            name='unit_price_editable',
            field=models.BooleanField(default=True),
        ),
    ]
