# Generated by Django 4.2.30 on 2026-06-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapi', '0003_businesssetting_ordertype'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='businesssetting',
            constraint=models.UniqueConstraint(fields=('company',), name='unique_business_setting_company'),
        ),
    ]
