# Generated by Django 4.2.30 on 2026-06-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapi', '0004_businesssetting_unique_business_setting_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssetting',
            name='enable_delivery_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesssetting',
            name='enable_dine_in_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesssetting',
            name='enable_online_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesssetting',
            name='enable_takeaway_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='OrderType',
        ),
    ]
