# Generated by Django 4.2.30 on 2026-06-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapi', '0005_businesssetting_enable_delivery_orders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesssetting',
            name='enable_delivery_orders',
        ),
        migrations.RemoveField(
            model_name='businesssetting',
            name='enable_dine_in_orders',
        ),
        migrations.RemoveField(
            model_name='businesssetting',
            name='enable_online_orders',
        ),
        migrations.RemoveField(
            model_name='businesssetting',
            name='enable_takeaway_orders',
        ),
        migrations.AddField(
            model_name='businesssetting',
            name='enable_delivery_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesssetting',
            name='enable_take_order',
            field=models.BooleanField(default=True),
        ),
    ]
