# Generated by Django 4.2.30 on 2026-06-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapi', '0006_remove_businesssetting_enable_delivery_orders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesssetting',
            name='enable_delivery_order',
        ),
        migrations.RemoveField(
            model_name='businesssetting',
            name='enable_take_order',
        ),
        migrations.AddField(
            model_name='businesssetting',
            name='order_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
