# Generated by Django 4.2.30 on 2026-06-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapi', '0008_option'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='setting',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='company',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
