# Generated by Django 4.2.30 on 2026-06-21 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Deactive'), (2, 'Delete')], default=0, help_text='0: Active, 1: Inactive, 2: Deleted. Higher values are reserved for model-specific lifecycle states.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('register_status', models.CharField(default='closed', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.company')),
                ('used_by', models.ForeignKey(blank=True, db_column='used_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_registers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegistersHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Deactive'), (2, 'Delete')], default=0, help_text='0: Active, 1: Inactive, 2: Deleted. Higher values are reserved for model-specific lifecycle states.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payment_type_id', models.PositiveIntegerField(default=0)),
                ('order_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('entry_type', models.CharField(choices=[('register-opening', 'Register Opening'), ('register-closing', 'Register Closing'), ('register-cash-in', 'Cash In'), ('register-cash-out', 'Cash Out'), ('register-cash-delete', 'Cash Delete'), ('register-order-payment', 'Order Payment'), ('register-order-change', 'Order Change'), ('register-order-voucher', 'Order Voucher'), ('register-refund', 'Refund'), ('register-account-pay', 'Account Pay'), ('register-account-in', 'Account In')], db_column='action', max_length=50)),
                ('amount', models.DecimalField(db_column='value', decimal_places=5, max_digits=18)),
                ('note', models.TextField(blank=True, db_column='description', null=True)),
                ('balance_before', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('balance_after', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.company')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='registers.register')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registers_history',
            },
        ),
    ]
