# Generated by Django 4.2.30 on 2026-06-21 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Deactive'), (2, 'Delete')], default=0, help_text='0: Active, 1: Inactive, 2: Deleted. Higher values are reserved for model-specific lifecycle states.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, null=True)),
                ('media_id', models.PositiveBigIntegerField(default=0)),
                ('value', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('recurring', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, default='expense', max_length=80, null=True)),
                ('active', models.BooleanField(default=False)),
                ('group_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('occurrence', models.CharField(blank=True, max_length=80, null=True)),
                ('occurrence_value', models.CharField(blank=True, max_length=80, null=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Deactive'), (2, 'Delete')], default=0, help_text='0: Active, 1: Inactive, 2: Deleted. Higher values are reserved for model-specific lifecycle states.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('account', models.CharField(blank=True, max_length=120)),
                ('category_identifier', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'transactions_accounts',
                'ordering': ['category_identifier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionActionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Deactive'), (2, 'Delete')], default=0, help_text='0: Active, 1: Inactive, 2: Deleted. Higher values are reserved for model-specific lifecycle states.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('on', models.CharField(default='', max_length=80)),
                ('action', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], max_length=20)),
                ('do', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], default='increase', max_length=20)),
                ('locked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'transactions_actions_rules',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionBalanceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Deactive'), (2, 'Delete')], default=0, help_text='0: Active, 1: Inactive, 2: Deleted. Higher values are reserved for model-specific lifecycle states.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('income', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('expense', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('closing_balance', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transactions_balance_days',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionBalanceMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Deactive'), (2, 'Delete')], default=0, help_text='0: Active, 1: Inactive, 2: Deleted. Higher values are reserved for model-specific lifecycle states.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('income', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('expense', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('closing_balance', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transactions_balance_months',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Deactive'), (2, 'Delete')], default=0, help_text='0: Active, 1: Inactive, 2: Deleted. Higher values are reserved for model-specific lifecycle states.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10)),
                ('procurement_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('order_refund_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('order_refund_product_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('order_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('order_product_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('order_payment_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('register_history_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('customer_account_history_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=180)),
                ('type', models.CharField(blank=True, max_length=80)),
                ('transaction_status', models.CharField(db_column='transaction_status', default='pending', max_length=30)),
                ('value', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('trigger_date', models.DateTimeField(blank=True, null=True)),
                ('is_reflection', models.BooleanField(default=False)),
                ('reflection_source_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.company')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='accounting.transactionactionrule')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='accounting.transaction')),
                ('transaction_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='histories', to='accounting.transactionaccount')),
            ],
            options={
                'db_table': 'transactions_histories',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
