# Generated by Django 4.2.30 on 2026-06-13 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetransactionhistory',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_histories', to='accounting.transactionaccount'),
        ),
        migrations.AddField(
            model_name='activetransactionhistory',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='activetransactionhistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='activetransactionhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activetransactionhistory',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_histories', to='accounting.transaction'),
        ),
        migrations.AddField(
            model_name='activetransactionhistory',
            name='transaction_history',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_marker', to='accounting.transactionhistory'),
        ),
        migrations.AddField(
            model_name='accountingsetting',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='accountingsetting',
            name='cogs_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cogs_settings', to='accounting.transactionaccount'),
        ),
        migrations.AddField(
            model_name='accountingsetting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='accountingsetting',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingsetting',
            name='expense_accounts',
            field=models.ManyToManyField(blank=True, related_name='expense_settings', to='accounting.transactionaccount'),
        ),
        migrations.AddField(
            model_name='accountingsetting',
            name='inventory_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_settings', to='accounting.transactionaccount'),
        ),
        migrations.AddField(
            model_name='accountingsetting',
            name='order_cash_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_cash_settings', to='accounting.transactionaccount'),
        ),
        migrations.AddField(
            model_name='accountingsetting',
            name='paid_expense_offset_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_expense_offset_settings', to='accounting.transactionaccount'),
        ),
        migrations.AddField(
            model_name='accountingsetting',
            name='procurement_cash_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_cash_settings', to='accounting.transactionaccount'),
        ),
        migrations.AddField(
            model_name='accountingsetting',
            name='procurement_payable_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_payable_settings', to='accounting.transactionaccount'),
        ),
        migrations.AddField(
            model_name='accountingsetting',
            name='receivable_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivable_settings', to='accounting.transactionaccount'),
        ),
        migrations.AddField(
            model_name='accountingsetting',
            name='sales_revenue_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_revenue_settings', to='accounting.transactionaccount'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionbalancemonth',
            unique_together={('branch', 'account', 'year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='transactionbalanceday',
            unique_together={('branch', 'account', 'balance_date')},
        ),
        migrations.AlterUniqueTogether(
            name='transactionaccount',
            unique_together={('branch', 'code')},
        ),
        migrations.AddConstraint(
            model_name='accountingsetting',
            constraint=models.UniqueConstraint(fields=('company', 'branch'), name='unique_accounting_setting_branch'),
        ),
    ]
