# Generated by Django 4.2.30 on 2026-06-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionActionRule',
        ),
    ]
