# Generated by Django 4.2.30 on 2026-06-12 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activetransactionhistory',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_histories', to='accounting.transactionaccount'),
        ),
        migrations.AddField(
            model_name='activetransactionhistory',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='activetransactionhistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='activetransactionhistory',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_histories', to='accounting.transaction'),
        ),
        migrations.AddField(
            model_name='activetransactionhistory',
            name='transaction_history',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_marker', to='accounting.transactionhistory'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionbalancemonth',
            unique_together={('branch', 'account', 'year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='transactionbalanceday',
            unique_together={('branch', 'account', 'balance_date')},
        ),
        migrations.AlterUniqueTogether(
            name='transactionaccount',
            unique_together={('branch', 'code')},
        ),
    ]
