# Generated by Django 4.2.30 on 2026-06-16 07:21

from django.db import migrations, models
import django.db.models.deletion


def backfill_nexopos_account_fields(apps, schema_editor):
    TransactionAccount = apps.get_model('accounting', 'TransactionAccount')
    category_map = {
        "asset": "assets",
        "liability": "liabilities",
        "income": "revenues",
        "expense": "expenses",
        "equity": "equity",
    }
    for account in TransactionAccount.objects.all().iterator():
        account.account = account.account or account.code or str(account.id).zfill(5)
        account.category_identifier = (
            account.category_identifier
            or category_map.get(account.account_type)
            or account.account_type
            or ""
        )
        account.sub_category_id = account.sub_category_id or account.parent_id
        account.save(update_fields=["account", "category_identifier", "sub_category"])


def noop_reverse(apps, schema_editor):
    pass


def rename_void_rule_events(apps, schema_editor):
    TransactionActionRule = apps.get_model('accounting', 'TransactionActionRule')
    Transaction = apps.get_model('accounting', 'Transaction')

    TransactionActionRule.objects.filter(event_key='paid_order_voided').update(event_key='order_paid_voided')
    TransactionActionRule.objects.filter(event_key='unpaid_order_voided').update(event_key='order_unpaid_voided')
    Transaction.objects.filter(event_key='paid_order_voided').update(event_key='order_paid_voided')
    Transaction.objects.filter(event_key='unpaid_order_voided').update(event_key='order_unpaid_voided')


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionaccount',
            unique_together={('branch', 'code')},
        ),
        migrations.AddField(
            model_name='transactionaccount',
            name='account',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='transactionaccount',
            name='category_identifier',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='transactionaccount',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nexopos_sub_accounts', to='accounting.transactionaccount'),
        ),
        migrations.RunPython(backfill_nexopos_account_fields, noop_reverse),
        migrations.RunPython(rename_void_rule_events, noop_reverse),
        migrations.AlterUniqueTogether(
            name='transactionaccount',
            unique_together={('branch', 'code'), ('branch', 'account')},
        ),
    ]
