# Generated by Django 4.2.30 on 2026-06-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_transactionaccount_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountingSetting',
        ),
    ]
