# Generated by Django 4.2.30 on 2026-06-16 13:32

from datetime import date

from django.db import migrations, models


def backfill_month_balance_dates(apps, schema_editor):
    TransactionBalanceMonth = apps.get_model("accounting", "TransactionBalanceMonth")
    for balance in TransactionBalanceMonth.objects.all().iterator():
        balance.date = date(int(balance.year), int(balance.month), 1)
        balance.income = balance.total_credit
        balance.expense = balance.total_debit
        balance.save(update_fields=["date", "income", "expense"])


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('accounting', '0005_align_transaction_models_with_nexopos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionaccount',
            options={'ordering': ['category_identifier', 'name']},
        ),
        migrations.AlterModelOptions(
            name='transactionbalanceday',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='transactionbalancemonth',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='transactionaccount',
            unique_together={('branch', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='transactionbalanceday',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='transactionbalancemonth',
            unique_together=set(),
        ),
        migrations.RenameField(
            model_name='transactionbalanceday',
            old_name='balance_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transactionbalanceday',
            old_name='total_credit',
            new_name='income',
        ),
        migrations.RenameField(
            model_name='transactionbalanceday',
            old_name='total_debit',
            new_name='expense',
        ),
        migrations.AlterField(
            model_name='transactionbalanceday',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionbalancemonth',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionbalancemonth',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transactionbalancemonth',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.RunPython(backfill_month_balance_dates, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='transactionbalanceday',
            unique_together={('branch', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='transactionbalancemonth',
            unique_together={('branch', 'date')},
        ),
        migrations.RemoveField(
            model_name='transactionaccount',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='transactionaccount',
            name='code',
        ),
        migrations.RemoveField(
            model_name='transactionaccount',
            name='current_balance',
        ),
        migrations.RemoveField(
            model_name='transactionaccount',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='transactionaccount',
            name='is_system',
        ),
        migrations.RemoveField(
            model_name='transactionaccount',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='transactionbalanceday',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transactionbalancemonth',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transactionbalancemonth',
            name='month',
        ),
        migrations.RemoveField(
            model_name='transactionbalancemonth',
            name='total_credit',
        ),
        migrations.RemoveField(
            model_name='transactionbalancemonth',
            name='total_debit',
        ),
        migrations.RemoveField(
            model_name='transactionbalancemonth',
            name='year',
        ),
    ]
