# Generated by Django 4.2.30 on 2026-06-15 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rewards', '0002_alter_rewardredemption_customer_and_more'),
        ('customers', '0003_customercoupon_customerreward_remove_customer_branch_and_more'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcoupon',
            name='customer_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_orders', to='customers.customercoupon'),
        ),
        migrations.AlterField(
            model_name='couponcustomer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CustomerCoupon',
        ),
    ]
