# Generated by Django 4.2.30 on 2026-07-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_company_name_alter_branch_unique_together'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coupon',
            unique_together={('branch', 'code'), ('branch', 'name')},
        ),
    ]
