# Generated by Codex on 2026-07-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0002_alter_coupon_unique_together"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CouponCustomer",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="customers_id",
        ),
    ]
