# Generated by Django 4.2.30 on 2026-05-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registers', '0001_initial'),
        ('payments', '0001_initial'),
        ('organizations', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepayment',
            name='sale_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.saleorder'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_payments', to='registers.cashiershift'),
        ),
        migrations.AddField(
            model_name='refundpayment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='refundpayment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='refundpayment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_payments', to='payments.paymentmethod'),
        ),
        migrations.AddField(
            model_name='refundpayment',
            name='return_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_payments', to='sales.returnorder'),
        ),
        migrations.AddField(
            model_name='refundpayment',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_payments', to='registers.cashiershift'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.company'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('branch', 'code')},
        ),
    ]
