# Generated by Django 4.2.30 on 2026-06-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remove_expenseentry_payment_method_and_more'),
        ('registers', '0003_remove_cashregisterentry_payment_method_and_more'),
        ('purchases', '0004_remove_purchasepayment_payment_method_and_more'),
        ('payments', '0005_simplify_payment_method_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundpayment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='salepayment',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='refundpayment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('bank', 'Bank'), ('partial', 'Partial'), ('card', 'Card')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('bank', 'Bank'), ('partial', 'Partial'), ('card', 'Card')], default='cash', max_length=20),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
