# Generated by Django 4.2.30 on 2026-06-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundpayment',
            name='payment_type',
            field=models.CharField(choices=[('cash-payment', 'Cash'), ('bank-payment', 'Bank Payment'), ('account-payment', 'Customer Account')], default='cash-payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='payment_type',
            field=models.CharField(choices=[('cash-payment', 'Cash'), ('bank-payment', 'Bank Payment'), ('account-payment', 'Customer Account')], default='cash-payment', max_length=20),
        ),
    ]
