# Generated by Django 4.2.30 on 2026-06-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_refundpayment_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundpayment',
            name='payment_type',
            field=models.CharField(default='cash-payment', max_length=80),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='payment_type',
            field=models.CharField(default='cash-payment', max_length=80),
        ),
    ]
