# Generated by Django 4.2.30 on 2026-06-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_refundpayment_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttype',
            name='is_enabled',
        ),
    ]
