# Generated by Django 4.2.30 on 2026-06-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_company_branch_state_relation'),
        ('payments', '0010_remove_paymenttype_is_enabled'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymenttype',
            unique_together={('branch', 'identifier'), ('branch', 'label')},
        ),
    ]
