# Generated by Django 4.2.30 on 2026-06-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockledger',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='stockledger',
            name='company',
        ),
        migrations.RemoveField(
            model_name='stockledger',
            name='product',
        ),
        migrations.DeleteModel(
            name='StockAdjustment',
        ),
        migrations.DeleteModel(
            name='StockLedger',
        ),
    ]
