# Generated by Django 4.2.30 on 2026-05-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('organizations', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklot',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_lots', to='purchases.purchaseitem'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lots', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='inventory.stocklot'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='lowstockalert',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='lowstockalert',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='lowstockalert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_alerts', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='lowstockalert',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_alerts', to='catalog.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='stocktransfer',
            unique_together={('branch', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='stockadjustment',
            unique_together={('branch', 'code')},
        ),
    ]
