# Generated by Django 4.2.30 on 2026-06-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_use_product_without_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('added', 'Add'), ('deleted', 'Delete'), ('defective', 'Defective'), ('lost', 'Lost'), ('set', 'Set')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='entry_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('sale_return', 'Sale Return'), ('adjustment_in', 'Adjustment In'), ('adjustment_out', 'Adjustment Out'), ('adjustment_set', 'Adjustment Set'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('opening_stock', 'Opening Stock')], max_length=20),
        ),
    ]
