# Generated by Django 4.2.30 on 2026-06-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_stockadjustment_adjustment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklot',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='stocklot',
            name='company',
        ),
        migrations.RemoveField(
            model_name='stocklot',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stocklot',
            name='purchase_item',
        ),
        migrations.AlterUniqueTogether(
            name='stocktransfer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='destination_branch',
        ),
        migrations.RemoveField(
            model_name='stocktransferitem',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='stocktransferitem',
            name='company',
        ),
        migrations.RemoveField(
            model_name='stocktransferitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stocktransferitem',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='stockledger',
            name='lot',
        ),
        migrations.DeleteModel(
            name='LowStockAlert',
        ),
        migrations.DeleteModel(
            name='StockLot',
        ),
        migrations.DeleteModel(
            name='StockTransfer',
        ),
        migrations.DeleteModel(
            name='StockTransferItem',
        ),
    ]
