# Generated by Django 4.2.30 on 2026-06-15 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0003_customercoupon_customerreward_remove_customer_branch_and_more'),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardredemption',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rewardredemption',
            name='customer_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_redemptions', to='customers.customercoupon'),
        ),
        migrations.DeleteModel(
            name='CustomerRewardBalance',
        ),
    ]
