class ErrorCodes:
    BAD_REQUEST = "BAD_REQUEST"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNAUTHORIZED = "UNAUTHORIZED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    FORBIDDEN = "FORBIDDEN"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    NOT_FOUND = "NOT_FOUND"
    SERVER_ERROR = "SERVER_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    DATABASE_ERROR = "DATABASE_ERROR"

    COMPANY_NOT_FOUND = "COMPANY_NOT_FOUND"
    ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND"
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND"
    INVALID_PERMISSIONS = "INVALID_PERMISSIONS"
    ADMINISTRATOR_ROLE_DELETE_FORBIDDEN = "ADMINISTRATOR_ROLE_DELETE_FORBIDDEN"
    ROLE_IN_USE = "ROLE_IN_USE"

    INVALID_OTP = "INVALID_OTP"
    OTP_EXPIRED = "OTP_EXPIRED"
    PHONE_REQUIRED = "PHONE_REQUIRED"
    UNSUPPORTED_PROVIDER = "UNSUPPORTED_PROVIDER"
    PROVIDER_USER_ID_REQUIRED = "PROVIDER_USER_ID_REQUIRED"

    GOOGLE_CLIENT_ID_NOT_CONFIGURED = "GOOGLE_CLIENT_ID_NOT_CONFIGURED"
    GOOGLE_ID_TOKEN_REQUIRED = "GOOGLE_ID_TOKEN_REQUIRED"
    INVALID_GOOGLE_ID_TOKEN = "INVALID_GOOGLE_ID_TOKEN"
    GOOGLE_TOKEN_AUDIENCE_INVALID = "GOOGLE_TOKEN_AUDIENCE_INVALID"
    GOOGLE_TOKEN_ISSUER_INVALID = "GOOGLE_TOKEN_ISSUER_INVALID"


HTTP_STATUS_DEFAULT_CODES = {
    400: ErrorCodes.BAD_REQUEST,
    401: ErrorCodes.UNAUTHORIZED,
    403: ErrorCodes.FORBIDDEN,
    404: ErrorCodes.NOT_FOUND,
    422: ErrorCodes.VALIDATION_ERROR,
    500: ErrorCodes.SERVER_ERROR,
    503: ErrorCodes.SERVICE_UNAVAILABLE,
}
