# Generated by Django 4.2.30 on 2026-06-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
