SOURCE_PERMISSION_CATALOG = [
    "create.users",
    "read.users",
    "update.users",
    "delete.users",
    "create.roles",
    "read.roles",
    "update.roles",
    "delete.roles",
    "update.core",
    "manage.profile",
    "manage.options",
    "manage.modules",
    "read.dashboard",
    "pos.create.categories",
    "pos.read.categories",
    "pos.update.categories",
    "pos.delete.categories",
    "pos.create.customers",
    "pos.read.customers",
    "pos.update.customers",
    "pos.delete.customers",
    "pos.import.customers",
    "pos.customers.manage-account-history",
    "pos.create.customers-groups",
    "pos.read.customers-groups",
    "pos.update.customers-groups",
    "pos.delete.customers-groups",
    "pos.create.coupons",
    "pos.read.coupons",
    "pos.update.coupons",
    "pos.delete.coupons",
    "pos.upload.medias",
    "pos.see.medias",
    "pos.update.medias",
    "pos.delete.medias",
    "pos.create.orders",
    "pos.read.orders",
    "pos.update.orders",
    "pos.delete.orders",
    "pos.void.orders",
    "pos.refund.orders",
    "pos.make-payment.orders",
    "pos.create.orders-instalments",
    "pos.read.orders-instalments",
    "pos.update.orders-instalments",
    "pos.delete.orders-instalments",
    "pos.create.procurements",
    "pos.read.procurements",
    "pos.update.procurements",
    "pos.delete.procurements",
    "pos.create.providers",
    "pos.read.providers",
    "pos.update.providers",
    "pos.delete.providers",
    "pos.create.products",
    "pos.read.products",
    "pos.update.products",
    "pos.delete.products",
    "pos.create.products-labels",
    "pos.convert.products-units",
    "pos.create.products-units",
    "pos.read.products-units",
    "pos.update.products-units",
    "pos.delete.products-units",
    "pos.read.products-history",
    "pos.make.products-adjustments",
    "pos.create.registers",
    "pos.read.registers",
    "pos.update.registers",
    "pos.delete.registers",
    "pos.use.registers",
    "pos.create.rewards",
    "pos.read.rewards",
    "pos.update.rewards",
    "pos.delete.rewards",
    "pos.create.taxes",
    "pos.read.taxes",
    "pos.update.taxes",
    "pos.delete.taxes",
    "pos.create.transactions",
    "pos.read.transactions",
    "pos.update.transactions",
    "pos.delete.transactions",
    "pos.create.transactions-history",
    "pos.read.transactions-history",
    "pos.update.transactions-history",
    "pos.delete.transactions-history",
    "pos.create.transactions-account",
    "pos.read.transactions-account",
    "pos.update.transactions-account",
    "pos.delete.transactions-account",
    "pos.manage-payments-types",
    "pos.reports.sales",
    "pos.reports.products-report",
    "pos.reports.best_sales",
    "pos.reports.transactions",
    "pos.reports.yearly",
    "pos.reports.customers",
    "pos.reports.inventory",
    "pos.reports.customers-statement",
    "pos.reports.payment-types",
    "pos.reports.low-stock",
    "pos.reports.stock-history",
    "pos.pos.edit-purchase-price",
    "pos.pos.edit-settings",
    "pos.pos.products-discount",
    "pos.pos.cart-discount",
    "pos.pos.delete-order-product",
    "pos.cart.product-discount",
    "pos.cart.product-price",
    "pos.cart.product-wholesale-price",
    "pos.cart.product-delete",
    "pos.cart.settings",
    "pos.cart.taxes",
    "pos.cart.comments",
    "pos.cart.order-type",
    "pos.cart.coupons",
    "pos.cart.products",
    "pos.cart.void",
    "pos.cart.discount",
    "pos.cart.hold",
    "pos.see.profile-widget",
    "pos.see.sale-card-widget",
    "pos.see.expense-card-widget",
    "pos.see.incomplete-sale-card-widget",
    "pos.see.orders-summary-widget",
    "pos.see.orders-chart-widget",
    "pos.see.best-customers-widget",
    "pos.see.best-cashier-widget",
]


PERMISSION_ALIASES = {
    "users_view": "read.users",
    "users_create": "create.users",
    "users_update": "update.users",
    "users_delete": "delete.users",
    "roles_view": "read.roles",
    "roles_create": "create.roles",
    "roles_update": "update.roles",
    "roles_delete": "delete.roles",
    "settings_view": "manage.options",
    "settings_update": "manage.options",
    "customers_view": "pos.read.customers",
    "customers_create": "pos.create.customers",
    "customers_update": "pos.update.customers",
    "customers_delete": "pos.delete.customers",
    "categories_view": "pos.read.categories",
    "categories_create": "pos.create.categories",
    "categories_update": "pos.update.categories",
    "categories_delete": "pos.delete.categories",
    "products_view": "pos.read.products",
    "products_create": "pos.create.products",
    "products_update": "pos.update.products",
    "products_delete": "pos.delete.products",
    "products_labels_create": "pos.create.products-labels",
    "product_units_view": "pos.read.products-units",
    "product_units_create": "pos.create.products-units",
    "product_units_update": "pos.update.products-units",
    "product_units_delete": "pos.delete.products-units",
    "product_units_convert": "pos.convert.products-units",
    "taxes_view": "pos.read.taxes",
    "taxes_create": "pos.create.taxes",
    "taxes_update": "pos.update.taxes",
    "taxes_delete": "pos.delete.taxes",
    "inventory_view": "pos.read.products-history",
    "inventory_adjust": "pos.make.products-adjustments",
    "purchases_view": "pos.read.procurements",
    "purchases_create": "pos.create.procurements",
    "purchases_update": "pos.update.procurements",
    "purchases_delete": "pos.delete.procurements",
    "purchases_pay": "pos.update.procurements",
    "providers_view": "pos.read.providers",
    "providers_create": "pos.create.providers",
    "providers_update": "pos.update.providers",
    "providers_delete": "pos.delete.providers",
    "sales_view": "pos.read.orders",
    "sales_create": "pos.create.orders",
    "sales_update": "pos.update.orders",
    "sales_void": "pos.void.orders",
    "returns_view": "pos.read.orders",
    "returns_create": "pos.refund.orders",
    "returns_approve": "pos.refund.orders",
    "payments_view": "pos.manage-payments-types",
    "payments_create": "pos.manage-payments-types",
    "payments_update": "pos.manage-payments-types",
    "payments_delete": "pos.manage-payments-types",
    "payments_collect_due": "pos.make-payment.orders",
    "media_view": "pos.see.medias",
    "media_upload": "pos.upload.medias",
    "media_update": "pos.update.medias",
    "media_delete": "pos.delete.medias",
    "cash_register_view": "pos.read.registers",
    "cash_register_create": "pos.create.registers",
    "cash_register_update": "pos.update.registers",
    "cash_register_delete": "pos.delete.registers",
    "cash_register_open": "pos.use.registers",
    "cash_register_close": "pos.use.registers",
    "cash_register_cash_in": "pos.use.registers",
    "cash_register_cash_out": "pos.use.registers",
    "expenses_view": "pos.read.transactions",
    "expenses_create": "pos.create.transactions",
    "expenses_update": "pos.update.transactions",
    "expenses_delete": "pos.delete.transactions",
    "reports_view": "pos.reports.sales",
    "promotions_view": "pos.read.coupons",
    "promotions_create": "pos.create.coupons",
    "promotions_update": "pos.update.coupons",
    "promotions_delete": "pos.delete.coupons",
    "rewards_view": "pos.read.rewards",
    "rewards_create": "pos.create.rewards",
    "rewards_update": "pos.update.rewards",
    "rewards_delete": "pos.delete.rewards",
    "price_override": "pos.cart.product-price",
    "manual_discount": "pos.cart.discount",
    "refund_order": "pos.refund.orders",
    "view_profit_report": "pos.reports.sales",
}


ROLE_NAMESPACE_ALIASES = {
    "store-administrator": "pos.store.administrator",
    "store-cashier": "pos.store.cashier",
    "store-customer": "pos.store.customer",
}


ROLE_CATALOG = [
    {
        "name": "Administrator",
        "namespace": "admin",
        "description": "Master role which can perform all actions like create users, install/update/delete modules and much more.",
        "flags": {
            "is_store_manager": True,
            "is_cashier": False,
        },
        "permissions": [
            "*",
        ],
    },
    {
        "name": "Store Administrator",
        "namespace": "pos.store.administrator",
        "description": "Has control over an entire store.",
        "flags": {
            "is_store_manager": True,
            "is_cashier": False,
        },
        "permissions": [
            "read.dashboard",
            "manage.profile",
            "manage.options",
            "pos.read.transactions",
            "pos.create.transactions",
            "pos.update.transactions",
            "pos.delete.transactions",
            "pos.read.transactions-history",
            "pos.create.transactions-history",
            "pos.update.transactions-history",
            "pos.delete.transactions-history",
            "pos.read.transactions-account",
            "pos.create.transactions-account",
            "pos.update.transactions-account",
            "pos.delete.transactions-account",
            "pos.read.categories",
            "pos.create.categories",
            "pos.update.categories",
            "pos.delete.categories",
            "pos.read.customers",
            "pos.create.customers",
            "pos.update.customers",
            "pos.delete.customers",
            "pos.customers.manage-account-history",
            "pos.read.customers-groups",
            "pos.create.customers-groups",
            "pos.update.customers-groups",
            "pos.delete.customers-groups",
            "pos.read.coupons",
            "pos.create.coupons",
            "pos.update.coupons",
            "pos.delete.coupons",
            "pos.read.orders",
            "pos.create.orders",
            "pos.update.orders",
            "pos.delete.orders",
            "pos.void.orders",
            "pos.refund.orders",
            "pos.make-payment.orders",
            "pos.read.procurements",
            "pos.create.procurements",
            "pos.update.procurements",
            "pos.delete.procurements",
            "pos.read.providers",
            "pos.create.providers",
            "pos.update.providers",
            "pos.delete.providers",
            "pos.read.products",
            "pos.create.products",
            "pos.update.products",
            "pos.delete.products",
            "pos.read.products-history",
            "pos.make.products-adjustments",
            "pos.read.products-units",
            "pos.create.products-units",
            "pos.update.products-units",
            "pos.delete.products-units",
            "pos.read.registers",
            "pos.create.registers",
            "pos.update.registers",
            "pos.delete.registers",
            "pos.use.registers",
            "pos.read.rewards",
            "pos.create.rewards",
            "pos.update.rewards",
            "pos.delete.rewards",
            "pos.reports.sales",
            "pos.reports.transactions",
            "pos.reports.yearly",
            "pos.reports.inventory",
            "pos.reports.low-stock",
            "pos.reports.stock-history",
            "pos.read.taxes",
            "pos.create.taxes",
            "pos.update.taxes",
            "pos.delete.taxes",
            "pos.manage-payments-types",
            "pos.cart.product-discount",
            "pos.cart.product-price",
            "pos.cart.product-delete",
            "pos.cart.settings",
            "pos.cart.taxes",
            "pos.cart.comments",
            "pos.cart.order-type",
            "pos.cart.coupons",
            "pos.cart.products",
            "pos.cart.void",
            "pos.cart.discount",
            "pos.cart.hold",
        ],
    },
    {
        "name": "Store Cashier",
        "namespace": "pos.store.cashier",
        "description": "Handles checkout, due collection, and shift activity without stock control.",
        "flags": {
            "is_store_manager": False,
            "is_cashier": True,
        },
        "permissions": [
            "read.dashboard",
            "manage.profile",
            "pos.read.customers",
            "pos.create.customers",
            "pos.update.customers",
            "pos.customers.manage-account-history",
            "pos.read.orders",
            "pos.create.orders",
            "pos.update.orders",
            "pos.void.orders",
            "pos.refund.orders",
            "pos.make-payment.orders",
            "pos.read.orders-instalments",
            "pos.create.orders-instalments",
            "pos.update.orders-instalments",
            "pos.read.registers",
            "pos.use.registers",
            "pos.cart.product-discount",
            "pos.cart.product-price",
            "pos.cart.product-delete",
            "pos.cart.settings",
            "pos.cart.taxes",
            "pos.cart.comments",
            "pos.cart.order-type",
            "pos.cart.coupons",
            "pos.cart.void",
            "pos.cart.discount",
            "pos.cart.hold",
        ],
    },
    {
        "name": "User",
        "namespace": "user",
        "description": "Basic company user without operational access until permissions are assigned.",
        "flags": {
            "is_store_manager": False,
            "is_cashier": False,
        },
        "permissions": [],
    },
    {
        "name": "Store Customer",
        "namespace": "pos.store.customer",
        "description": "Customer-facing role without back-office access.",
        "flags": {
            "is_store_manager": False,
            "is_cashier": False,
        },
        "permissions": [],
    },
]


PERMISSION_CATALOG = {
    "users": ["view", "create", "update", "delete"],
    "roles": ["view", "create", "update", "delete"],
    "settings": ["view", "update"],
    "branches": ["view", "create", "update", "delete"],
    "customers": ["view", "create", "update", "delete", "import", "export"],
    "categories": ["view", "create", "update", "delete"],
    "products": ["view", "create", "update", "delete", "labels", "import", "export"],
    "product_units": ["view", "create", "update", "delete", "convert"],
    "taxes": ["view", "create", "update", "delete"],
    "inventory": ["view", "adjust", "transfer", "count"],
    "purchases": ["view", "create", "update", "delete", "receive", "pay"],
    "sales": ["view", "create", "update", "deliver", "void"],
    "returns": ["view", "create", "approve"],
    "payments": ["view", "create", "update", "delete", "collect_due"],
    "media": ["view", "upload", "update", "delete"],
    "cash_register": ["view", "create", "update", "delete", "open", "close", "cash_in", "cash_out"],
    "expenses": ["view", "create", "update", "delete"],
    "reports": ["view", "export"],
    "promotions": ["view", "create", "update", "delete"],
    "rewards": ["view", "create", "update", "delete"],
    "permissions_access": ["view", "create", "update", "delete"],
    "special": [
        "price_override",
        "manual_discount",
        "refund_order",
        "view_profit_report",
        "shift_difference_close",
    ],
}
