NEXOPOS_PERMISSION_CATALOG = [
    "create.users",
    "read.users",
    "update.users",
    "delete.users",
    "create.roles",
    "read.roles",
    "update.roles",
    "delete.roles",
    "update.core",
    "manage.profile",
    "manage.options",
    "manage.modules",
    "read.dashboard",
    "nexopos.create.categories",
    "nexopos.read.categories",
    "nexopos.update.categories",
    "nexopos.delete.categories",
    "nexopos.create.customers",
    "nexopos.read.customers",
    "nexopos.update.customers",
    "nexopos.delete.customers",
    "nexopos.import.customers",
    "nexopos.customers.manage-account-history",
    "nexopos.create.customers-groups",
    "nexopos.read.customers-groups",
    "nexopos.update.customers-groups",
    "nexopos.delete.customers-groups",
    "nexopos.create.coupons",
    "nexopos.read.coupons",
    "nexopos.update.coupons",
    "nexopos.delete.coupons",
    "nexopos.upload.medias",
    "nexopos.see.medias",
    "nexopos.update.medias",
    "nexopos.delete.medias",
    "nexopos.create.orders",
    "nexopos.read.orders",
    "nexopos.update.orders",
    "nexopos.delete.orders",
    "nexopos.void.orders",
    "nexopos.refund.orders",
    "nexopos.make-payment.orders",
    "nexopos.create.orders-instalments",
    "nexopos.read.orders-instalments",
    "nexopos.update.orders-instalments",
    "nexopos.delete.orders-instalments",
    "nexopos.create.procurements",
    "nexopos.read.procurements",
    "nexopos.update.procurements",
    "nexopos.delete.procurements",
    "nexopos.create.providers",
    "nexopos.read.providers",
    "nexopos.update.providers",
    "nexopos.delete.providers",
    "nexopos.create.products",
    "nexopos.read.products",
    "nexopos.update.products",
    "nexopos.delete.products",
    "nexopos.convert.products-units",
    "nexopos.create.products-units",
    "nexopos.read.products-units",
    "nexopos.update.products-units",
    "nexopos.delete.products-units",
    "nexopos.read.products-history",
    "nexopos.make.products-adjustments",
    "nexopos.create.registers",
    "nexopos.read.registers",
    "nexopos.update.registers",
    "nexopos.delete.registers",
    "nexopos.use.registers",
    "nexopos.create.rewards",
    "nexopos.read.rewards",
    "nexopos.update.rewards",
    "nexopos.delete.rewards",
    "nexopos.create.taxes",
    "nexopos.read.taxes",
    "nexopos.update.taxes",
    "nexopos.delete.taxes",
    "nexopos.create.transactions",
    "nexopos.read.transactions",
    "nexopos.update.transactions",
    "nexopos.delete.transactions",
    "nexopos.create.transactions-history",
    "nexopos.read.transactions-history",
    "nexopos.update.transactions-history",
    "nexopos.delete.transactions-history",
    "nexopos.create.transactions-account",
    "nexopos.read.transactions-account",
    "nexopos.update.transactions-account",
    "nexopos.delete.transactions-account",
    "nexopos.manage-payments-types",
    "nexopos.reports.sales",
    "nexopos.reports.products-report",
    "nexopos.reports.best_sales",
    "nexopos.reports.transactions",
    "nexopos.reports.yearly",
    "nexopos.reports.customers",
    "nexopos.reports.inventory",
    "nexopos.reports.customers-statement",
    "nexopos.reports.payment-types",
    "nexopos.reports.low-stock",
    "nexopos.reports.stock-history",
    "nexopos.pos.edit-purchase-price",
    "nexopos.pos.edit-settings",
    "nexopos.pos.products-discount",
    "nexopos.pos.cart-discount",
    "nexopos.pos.delete-order-product",
    "nexopos.cart.product-discount",
    "nexopos.cart.product-price",
    "nexopos.cart.product-wholesale-price",
    "nexopos.cart.product-delete",
    "nexopos.cart.settings",
    "nexopos.cart.taxes",
    "nexopos.cart.comments",
    "nexopos.cart.order-type",
    "nexopos.cart.coupons",
    "nexopos.cart.products",
    "nexopos.cart.void",
    "nexopos.cart.discount",
    "nexopos.cart.hold",
    "nexopos.see.profile-widget",
    "nexopos.see.sale-card-widget",
    "nexopos.see.expense-card-widget",
    "nexopos.see.incomplete-sale-card-widget",
    "nexopos.see.orders-summary-widget",
    "nexopos.see.orders-chart-widget",
    "nexopos.see.best-customers-widget",
    "nexopos.see.best-cashier-widget",
]


PERMISSION_ALIASES = {
    "users_view": "read.users",
    "users_create": "create.users",
    "users_update": "update.users",
    "users_delete": "delete.users",
    "roles_view": "read.roles",
    "roles_create": "create.roles",
    "roles_update": "update.roles",
    "roles_delete": "delete.roles",
    "settings_view": "manage.options",
    "settings_update": "manage.options",
    "customers_view": "nexopos.read.customers",
    "customers_create": "nexopos.create.customers",
    "customers_update": "nexopos.update.customers",
    "customers_delete": "nexopos.delete.customers",
    "products_view": "nexopos.read.products",
    "products_create": "nexopos.create.products",
    "products_update": "nexopos.update.products",
    "products_delete": "nexopos.delete.products",
    "inventory_view": "nexopos.read.products-history",
    "inventory_adjust": "nexopos.make.products-adjustments",
    "purchases_view": "nexopos.read.procurements",
    "purchases_create": "nexopos.create.procurements",
    "purchases_update": "nexopos.update.procurements",
    "purchases_delete": "nexopos.delete.procurements",
    "purchases_pay": "nexopos.update.procurements",
    "sales_view": "nexopos.read.orders",
    "sales_create": "nexopos.create.orders",
    "sales_update": "nexopos.update.orders",
    "sales_void": "nexopos.void.orders",
    "returns_view": "nexopos.read.orders",
    "returns_create": "nexopos.refund.orders",
    "returns_approve": "nexopos.refund.orders",
    "payments_view": "nexopos.read.orders",
    "payments_create": "nexopos.make-payment.orders",
    "payments_update": "nexopos.make-payment.orders",
    "payments_delete": "nexopos.update.orders",
    "payments_collect_due": "nexopos.make-payment.orders",
    "cash_register_view": "nexopos.read.registers",
    "cash_register_open": "nexopos.use.registers",
    "cash_register_close": "nexopos.use.registers",
    "cash_register_cash_in": "nexopos.use.registers",
    "cash_register_cash_out": "nexopos.use.registers",
    "expenses_view": "nexopos.read.transactions",
    "expenses_create": "nexopos.create.transactions",
    "expenses_update": "nexopos.update.transactions",
    "expenses_delete": "nexopos.delete.transactions",
    "reports_view": "nexopos.reports.sales",
    "promotions_view": "nexopos.read.coupons",
    "promotions_create": "nexopos.create.coupons",
    "promotions_update": "nexopos.update.coupons",
    "promotions_delete": "nexopos.delete.coupons",
    "rewards_view": "nexopos.read.rewards",
    "rewards_create": "nexopos.create.rewards",
    "rewards_update": "nexopos.update.rewards",
    "rewards_delete": "nexopos.delete.rewards",
    "price_override": "nexopos.cart.product-price",
    "manual_discount": "nexopos.cart.discount",
    "refund_order": "nexopos.refund.orders",
    "view_profit_report": "nexopos.reports.sales",
}


ROLE_NAMESPACE_ALIASES = {
    "store-administrator": "nexopos.store.administrator",
    "store-cashier": "nexopos.store.cashier",
    "store-customer": "nexopos.store.customer",
}


ROLE_CATALOG = [
    {
        "name": "Administrator",
        "namespace": "admin",
        "description": "Master role which can perform all actions like create users, install/update/delete modules and much more.",
        "flags": {
            "is_store_manager": True,
            "is_cashier": False,
        },
        "permissions": [
            "*",
        ],
    },
    {
        "name": "Store Administrator",
        "namespace": "nexopos.store.administrator",
        "description": "Has control over an entire store.",
        "flags": {
            "is_store_manager": True,
            "is_cashier": False,
        },
        "permissions": [
            "read.dashboard",
            "manage.profile",
            "manage.options",
            "nexopos.read.transactions",
            "nexopos.create.transactions",
            "nexopos.update.transactions",
            "nexopos.delete.transactions",
            "nexopos.read.transactions-history",
            "nexopos.create.transactions-history",
            "nexopos.update.transactions-history",
            "nexopos.delete.transactions-history",
            "nexopos.read.transactions-account",
            "nexopos.create.transactions-account",
            "nexopos.update.transactions-account",
            "nexopos.delete.transactions-account",
            "nexopos.read.categories",
            "nexopos.create.categories",
            "nexopos.update.categories",
            "nexopos.delete.categories",
            "nexopos.read.customers",
            "nexopos.create.customers",
            "nexopos.update.customers",
            "nexopos.delete.customers",
            "nexopos.customers.manage-account-history",
            "nexopos.read.customers-groups",
            "nexopos.create.customers-groups",
            "nexopos.update.customers-groups",
            "nexopos.delete.customers-groups",
            "nexopos.read.coupons",
            "nexopos.create.coupons",
            "nexopos.update.coupons",
            "nexopos.delete.coupons",
            "nexopos.read.orders",
            "nexopos.create.orders",
            "nexopos.update.orders",
            "nexopos.delete.orders",
            "nexopos.void.orders",
            "nexopos.refund.orders",
            "nexopos.make-payment.orders",
            "nexopos.read.procurements",
            "nexopos.create.procurements",
            "nexopos.update.procurements",
            "nexopos.delete.procurements",
            "nexopos.read.providers",
            "nexopos.create.providers",
            "nexopos.update.providers",
            "nexopos.delete.providers",
            "nexopos.read.products",
            "nexopos.create.products",
            "nexopos.update.products",
            "nexopos.delete.products",
            "nexopos.read.products-history",
            "nexopos.make.products-adjustments",
            "nexopos.read.products-units",
            "nexopos.create.products-units",
            "nexopos.update.products-units",
            "nexopos.delete.products-units",
            "nexopos.read.registers",
            "nexopos.create.registers",
            "nexopos.update.registers",
            "nexopos.delete.registers",
            "nexopos.use.registers",
            "nexopos.read.rewards",
            "nexopos.create.rewards",
            "nexopos.update.rewards",
            "nexopos.delete.rewards",
            "nexopos.reports.sales",
            "nexopos.reports.transactions",
            "nexopos.reports.yearly",
            "nexopos.reports.inventory",
            "nexopos.reports.low-stock",
            "nexopos.reports.stock-history",
            "nexopos.read.taxes",
            "nexopos.create.taxes",
            "nexopos.update.taxes",
            "nexopos.delete.taxes",
            "nexopos.manage-payments-types",
            "nexopos.cart.product-discount",
            "nexopos.cart.product-price",
            "nexopos.cart.product-delete",
            "nexopos.cart.settings",
            "nexopos.cart.taxes",
            "nexopos.cart.comments",
            "nexopos.cart.order-type",
            "nexopos.cart.coupons",
            "nexopos.cart.products",
            "nexopos.cart.void",
            "nexopos.cart.discount",
            "nexopos.cart.hold",
        ],
    },
    {
        "name": "Store Cashier",
        "namespace": "nexopos.store.cashier",
        "description": "Handles checkout, due collection, and shift activity without stock control.",
        "flags": {
            "is_store_manager": False,
            "is_cashier": True,
        },
        "permissions": [
            "read.dashboard",
            "manage.profile",
            "nexopos.read.customers",
            "nexopos.create.customers",
            "nexopos.update.customers",
            "nexopos.customers.manage-account-history",
            "nexopos.read.orders",
            "nexopos.create.orders",
            "nexopos.update.orders",
            "nexopos.void.orders",
            "nexopos.refund.orders",
            "nexopos.make-payment.orders",
            "nexopos.read.orders-instalments",
            "nexopos.create.orders-instalments",
            "nexopos.update.orders-instalments",
            "nexopos.read.registers",
            "nexopos.use.registers",
            "nexopos.cart.product-discount",
            "nexopos.cart.product-price",
            "nexopos.cart.product-delete",
            "nexopos.cart.settings",
            "nexopos.cart.taxes",
            "nexopos.cart.comments",
            "nexopos.cart.order-type",
            "nexopos.cart.coupons",
            "nexopos.cart.void",
            "nexopos.cart.discount",
            "nexopos.cart.hold",
        ],
    },
    {
        "name": "User",
        "namespace": "user",
        "description": "Basic company user without operational access until permissions are assigned.",
        "flags": {
            "is_store_manager": False,
            "is_cashier": False,
        },
        "permissions": [],
    },
    {
        "name": "Store Customer",
        "namespace": "nexopos.store.customer",
        "description": "Customer-facing role without back-office access.",
        "flags": {
            "is_store_manager": False,
            "is_cashier": False,
        },
        "permissions": [],
    },
]


PERMISSION_CATALOG = {
    "users": ["view", "create", "update", "delete"],
    "roles": ["view", "create", "update", "delete"],
    "settings": ["view", "update"],
    "branches": ["view", "create", "update", "delete"],
    "customers": ["view", "create", "update", "delete", "import", "export"],
    "products": ["view", "create", "update", "delete", "import", "export"],
    "inventory": ["view", "adjust", "transfer", "count"],
    "purchases": ["view", "create", "update", "delete", "receive", "pay"],
    "sales": ["view", "create", "update", "void"],
    "returns": ["view", "create", "approve"],
    "payments": ["view", "create", "update", "delete", "collect_due"],
    "cash_register": ["view", "open", "close", "cash_in", "cash_out"],
    "expenses": ["view", "create", "update", "delete"],
    "reports": ["view", "export"],
    "promotions": ["view", "create", "update", "delete"],
    "rewards": ["view", "create", "update", "delete"],
    "permissions_access": ["view", "create", "update", "delete"],
    "special": [
        "price_override",
        "manual_discount",
        "refund_order",
        "view_profit_report",
        "shift_difference_close",
    ],
}
