ROLE_CATALOG = [
    {
        "name": "Administrator",
        "code": "administrator",
        "description": "Full company access across users, settings, stock, sales, and finance.",
        "flags": {
            "is_store_manager": True,
            "is_cashier": False,
        },
        "permissions": [
            "*",
        ],
    },
    {
        "name": "Store Administrator",
        "code": "store-administrator",
        "description": "Full branch operations with user and stock control, but not top-level company ownership.",
        "flags": {
            "is_store_manager": True,
            "is_cashier": False,
        },
        "permissions": [
            "branches_view",
            "branches_update",
            "customers_view",
            "customers_create",
            "customers_update",
            "customers_delete",
            "products_view",
            "products_create",
            "products_update",
            "products_delete",
            "inventory_view",
            "inventory_adjust",
            "inventory_transfer",
            "purchases_view",
            "purchases_create",
            "purchases_update",
            "purchases_receive",
            "sales_view",
            "sales_create",
            "sales_update",
            "sales_void",
            "returns_view",
            "returns_create",
            "returns_approve",
            "payments_view",
            "payments_create",
            "payments_collect_due",
            "cash_register_view",
            "cash_register_open",
            "cash_register_close",
            "cash_register_cash_in",
            "cash_register_cash_out",
            "expenses_view",
            "expenses_create",
            "expenses_update",
            "reports_view",
            "reports_export",
            "promotions_view",
            "promotions_create",
            "promotions_update",
            "rewards_view",
            "rewards_create",
            "rewards_update",
            "price_override",
            "manual_discount",
            "refund_order",
            "view_profit_report",
            "shift_difference_close",
        ],
    },
    {
        "name": "Store Manager",
        "code": "store-manager",
        "description": "Runs daily branch operations and approvals without full company control.",
        "flags": {
            "is_store_manager": True,
            "is_cashier": False,
        },
        "permissions": [
            "branches_view",
            "customers_view",
            "customers_create",
            "customers_update",
            "products_view",
            "inventory_view",
            "inventory_adjust",
            "inventory_transfer",
            "purchases_view",
            "purchases_create",
            "purchases_update",
            "purchases_receive",
            "sales_view",
            "sales_create",
            "sales_update",
            "returns_view",
            "returns_create",
            "returns_approve",
            "payments_view",
            "payments_create",
            "payments_collect_due",
            "cash_register_view",
            "cash_register_open",
            "cash_register_close",
            "cash_register_cash_in",
            "cash_register_cash_out",
            "expenses_view",
            "expenses_create",
            "reports_view",
            "reports_export",
            "promotions_view",
            "rewards_view",
            "price_override",
            "manual_discount",
            "refund_order",
            "shift_difference_close",
        ],
    },
    {
        "name": "Store Cashier",
        "code": "store-cashier",
        "description": "Handles checkout, due collection, and shift activity without stock control.",
        "flags": {
            "is_store_manager": False,
            "is_cashier": True,
        },
        "permissions": [
            "customers_view",
            "customers_create",
            "customers_update",
            "products_view",
            "sales_view",
            "sales_create",
            "payments_view",
            "payments_create",
            "payments_collect_due",
            "cash_register_view",
            "cash_register_open",
            "cash_register_close",
            "cash_register_cash_in",
            "cash_register_cash_out",
            "rewards_view",
            "returns_view",
            "returns_create",
        ],
    },
    {
        "name": "Inventory Manager",
        "code": "inventory-manager",
        "description": "Controls stock movement, product upkeep, receiving, and branch transfers.",
        "flags": {
            "is_store_manager": False,
            "is_cashier": False,
        },
        "permissions": [
            "products_view",
            "products_create",
            "products_update",
            "inventory_view",
            "inventory_adjust",
            "inventory_transfer",
            "inventory_count",
            "purchases_view",
            "purchases_create",
            "purchases_update",
            "purchases_receive",
            "reports_view",
        ],
    },
    {
        "name": "Purchase Manager",
        "code": "purchase-manager",
        "description": "Manages suppliers, purchase orders, inward stock, and procurement payments.",
        "flags": {
            "is_store_manager": False,
            "is_cashier": False,
        },
        "permissions": [
            "products_view",
            "inventory_view",
            "purchases_view",
            "purchases_create",
            "purchases_update",
            "purchases_receive",
            "reports_view",
        ],
    },
    {
        "name": "Accountant",
        "code": "accountant",
        "description": "Reviews payments, expenses, due amounts, and financial reports.",
        "flags": {
            "is_store_manager": False,
            "is_cashier": False,
        },
        "permissions": [
            "customers_view",
            "sales_view",
            "payments_view",
            "payments_collect_due",
            "cash_register_view",
            "rewards_view",
            "expenses_view",
            "expenses_create",
            "expenses_update",
            "reports_view",
            "reports_export",
            "view_profit_report",
        ],
    },
    {
        "name": "User",
        "code": "user",
        "description": "Basic company user without operational access until permissions are assigned.",
        "flags": {
            "is_store_manager": False,
            "is_cashier": False,
        },
        "permissions": [],
    },
    {
        "name": "Store Customer",
        "code": "store-customer",
        "description": "Customer-facing role without back-office access.",
        "flags": {
            "is_store_manager": False,
            "is_cashier": False,
        },
        "permissions": [],
    },
]


PERMISSION_CATALOG = {
    "users": ["view", "create", "update", "delete"],
    "roles": ["view", "create", "update", "delete"],
    "settings": ["view", "update"],
    "branches": ["view", "create", "update", "delete"],
    "customers": ["view", "create", "update", "delete", "import", "export"],
    "products": ["view", "create", "update", "delete", "import", "export"],
    "inventory": ["view", "adjust", "transfer", "count"],
    "purchases": ["view", "create", "update", "receive", "pay"],
    "sales": ["view", "create", "update", "void"],
    "returns": ["view", "create", "approve"],
    "payments": ["view", "create", "collect_due"],
    "cash_register": ["view", "open", "close", "cash_in", "cash_out"],
    "expenses": ["view", "create", "update", "delete"],
    "reports": ["view", "export"],
    "promotions": ["view", "create", "update", "delete"],
    "rewards": ["view", "create", "update", "delete"],
    "special": [
        "price_override",
        "manual_discount",
        "refund_order",
        "view_profit_report",
        "shift_difference_close",
    ],
}
