# Generated by Django 4.2.30 on 2026-06-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_dashboardmonth_dashboardday'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salessummarysnapshot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='salessummarysnapshot',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='salessummarysnapshot',
            name='company',
        ),
        migrations.DeleteModel(
            name='DayClosing',
        ),
        migrations.DeleteModel(
            name='SalesSummarySnapshot',
        ),
    ]
