# Generated by Django 4.2.30 on 2026-07-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tax',
            unique_together={('branch', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='taxgroup',
            unique_together={('branch', 'name')},
        ),
    ]
