# Generated by Django 4.2.30 on 2026-07-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_company_name_alter_branch_unique_together'),
        ('catalog', '0002_alter_tax_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('branch', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('branch', 'sku'), ('branch', 'barcode'), ('branch', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='scalerange',
            unique_together={('branch', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('branch', 'name'), ('branch', 'identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='unitgroup',
            unique_together={('branch', 'name')},
        ),
    ]
