# Generated by Django 4.2.30 on 2026-05-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_unique_together_product_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
