# Generated by Django 4.2.30 on 2026-05-27 09:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_branch_status_alter_company_status'),
        ('catalog', '0004_alter_product_unique_together_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('company', 'sku'), ('company', 'barcode')},
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='selling_price',
        ),
        migrations.CreateModel(
            name='ProductVariantBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Deactive'), (2, 'Delete')], default=0, help_text='0: Active, 1: Inactive, 2: Deleted. Higher values are reserved for model-specific lifecycle states.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('opening_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('max_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('stock_alert_enabled', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.company')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_settings', to='catalog.productvariant')),
            ],
            options={
                'unique_together': {('branch', 'variant')},
            },
        ),
    ]
