# Generated by Django 4.2.30 on 2026-05-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_sku_alter_product_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
