# Generated by Django 4.2.30 on 2026-05-31 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_delete_productimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='taxgroup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='unitgroup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='brand',
            name='code',
        ),
        migrations.RemoveField(
            model_name='category',
            name='code',
        ),
        migrations.RemoveField(
            model_name='taxgroup',
            name='code',
        ),
        migrations.RemoveField(
            model_name='unitgroup',
            name='code',
        ),
    ]
