# Generated by Django 4.2.30 on 2026-06-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_branch_status_alter_company_status'),
        ('catalog', '0010_alter_brand_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('branch', 'sku'), ('branch', 'barcode')},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('service', 'Service')], default='stock', max_length=20),
        ),
        migrations.DeleteModel(
            name='ProductBundleItem',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_group',
        ),
    ]
