# Generated by Django 4.2.30 on 2026-06-01 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_product_reorder_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='is_inclusive',
        ),
    ]
