# Generated by Django 4.2.30 on 2026-06-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_parent_alter_product_product_type_scalerange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunitquantity',
            name='barcode',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
