# Generated by Django 4.2.30 on 2026-06-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_productunitquantity_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthistory',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='company',
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='producthistorycombined',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='producthistorycombined',
            name='company',
        ),
        migrations.RemoveField(
            model_name='producthistorycombined',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='productsubitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productsubitem',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='productsubitem',
            name='company',
        ),
        migrations.RemoveField(
            model_name='productsubitem',
            name='parent_product',
        ),
        migrations.RemoveField(
            model_name='productsubitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsubitem',
            name='unit',
        ),
        migrations.AlterUniqueTogether(
            name='producttax',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='producttax',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='producttax',
            name='company',
        ),
        migrations.RemoveField(
            model_name='producttax',
            name='product',
        ),
        migrations.RemoveField(
            model_name='producttax',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='scalerange',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='scalerange',
            name='company',
        ),
        migrations.DeleteModel(
            name='ProductGallery',
        ),
        migrations.DeleteModel(
            name='ProductHistory',
        ),
        migrations.DeleteModel(
            name='ProductHistoryCombined',
        ),
        migrations.DeleteModel(
            name='ProductSubItem',
        ),
        migrations.DeleteModel(
            name='ProductTax',
        ),
        migrations.DeleteModel(
            name='ScaleRange',
        ),
    ]
