# Generated by Django 4.2.30 on 2026-06-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_remove_purchaseitem_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasepayment',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('bank', 'Bank'), ('partial', 'Partial'), ('card', 'Card')], default='cash', max_length=20),
        ),
    ]
