# Generated by Django 4.2.30 on 2026-06-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_purchasepayment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_type',
            field=models.CharField(default='cash-payment', max_length=80),
        ),
    ]
