# Generated by Django 4.2.30 on 2026-05-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('registers', '0001_initial'),
        ('payments', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='payments.paymentmethod'),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='registers.cashiershift'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.company'),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('branch', 'code')},
        ),
    ]
