# Generated by Django 4.2.30 on 2026-06-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expensecategory_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseentry',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online'), ('bank', 'Bank'), ('partial', 'Partial'), ('card', 'Card')], default='', max_length=20),
        ),
    ]
