# Generated by Django 4.2.30 on 2026-06-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remove_expenseentry_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseentry',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash-payment', 'Cash'), ('bank-payment', 'Bank Payment'), ('account-payment', 'Customer Account')], default='', max_length=20),
        ),
    ]
