# Generated by Django 4.2.30 on 2026-06-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expenseentry_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseentry',
            name='payment_type',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
