# Generated by Django 4.2.30 on 2026-07-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('company', 'name'), ('company', 'code')},
        ),
    ]
