# Generated by Django 4.2.30 on 2026-06-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_branch_status_alter_company_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='company',
            name='timezone',
        ),
        migrations.AddField(
            model_name='company',
            name='city_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.URLField(blank=True),
        ),
    ]
