# Generated by Django 4.2.30 on 2026-06-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_remove_company_currency_remove_company_timezone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='country',
        ),
    ]
